version: "3.0"
services:
  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - defvol:/var/www/wordpress
    networks:
      - defnet
    environment:
        - MSQL_USER=${MSQL_USER}
        - MSQL_PASS=${MSQL_PASS}
        - MSQL_DB=${MSQL_DB}
  mariadb:
    build: ./requirements/mariadb/
    networks:
      - defnet
    ports:
      - 3306:3306
    restart: always
  nginx:
    build: ./requirements/nginx
    ports:
      - 8080:8080
    restart: always
    networks:
      - defnet
    depends_on:
      - wordpress
    volumes:
      - defvol:/var/www/wordpress

networks:
  defnet:
    driver: bridge

volumes :
  defvol:
    driver: local
    driver_opts:
      type: none
      device: /tmp/wordpress
      o: bind
