version: "3.0"
services:
  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    volumes:
      - wp:/var/www/wordpress
    networks:
      - defnet
    environment:
        - MSQL_USER=${MSQL_USER}
        - MSQL_PASS=${MSQL_PASS}
        - MSQL_DB=${MSQL_DB}
  mariadb:
    build: ./requirements/mariadb/
    networks:
      - defnet
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    restart: always
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    networks:
      - defnet
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/wordpress

networks:
  defnet:
    driver: bridge

volumes :
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/debian/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/debian/data/mariadb
      o: bind
