version: "3.0"
services:
  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    environment:
        - MSQL_USER=${MSQL_USER}
        - MSQL_PASS=${MSQL_PASS}
        - MSQL_DB=${MSQL_DB}
  mariadb:
    build: ./requirements/mariadb/
    ports:
      - 3306:3306
    restart: always
  nginx:
    build: ./requirements/nginx
    ports:
      - 8080:80
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress

volumes :
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/debian/data/wordpress
      o: bind

